CREATE DATABASE IF NOT EXISTS MIPS;
USE MIPS;

CREATE TABLE MEMBER (
    MEMBER_IDX		BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID 		VARCHAR(50),
    PASSWD			VARCHAR(200),
    NICKNAME		VARCHAR(50),
    EMAIL			VARCHAR(200),
    BIRTH			TIMESTAMP,
    GENDER			VARCHAR(2),
    ADDRESS			VARCHAR(200),
    ROLE			VARCHAR(10),
    ACTIVE_YN		VARCHAR(1),
    CREATED_AT		TIMESTAMP,
    LAST_LOGIN		TIMESTAMP
);


INSERT INTO 
		MEMBER 
VALUES
	(1, 'test', 'test', 'test', 'test@naver.com', '1986-07-15', 'M', '서울시 강남구 논현동 25', 'USER', 'Y', '2024-05-04 12:00:00', '2024-05-06 10:30:28')
 