CREATE DATABASE IF NOT EXISTS MIPS;
USE MIPS;

CREATE TABLE MEMBER (
    MEMBER_IDX		BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID 		VARCHAR(50),
    PASSWD			VARCHAR(200),
    NICKNAME		VARCHAR(50),
    EMAIL			VARCHAR(200),
    BIRTH			TIMESTAMP,
    GENDER			VARCHAR(2),
    ADDRESS			VARCHAR(200),
    ROLE			VARCHAR(10),
    ACTIVE_YN		VARCHAR(1),
    CREATED_AT		TIMESTAMP,
    LAST_LOGIN		TIMESTAMP
);
